# Generated by Django 5.1.1 on 2025-10-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_job_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='job',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
